### ISSUE TITLE
gpa and Keybase don't see the keyring

### ISSUE THREAD

**Issue by gordonel** [romanz/trezor-agent#295]
OS: Ubuntu 18.04.3 LTS

I had a number of issues when trying to set up the agent, namely:
- wheel failed to build for hidapi due to `unknown file type .pyx` (solved by installing Pyrex and Cython)
- could not initialise gpg directory unless the UID matched the current username in the OS (had to use my system username to initialise the directory)

Now I'm trying to use gpa and add my PGP key to Keybase, but neither gpa nor Keybase can see it for some reason. I'm able to sign the messages just fine though.

gpa thinks that I have no keys whatsoever and prompts me to generate some, and `keybase pgp select` exits with `ERROR No PGP keys available to choose from`

**Comment by jonathancross** [comment]
Seems the keybase issue is solved?

**Comment by gordonel** [comment]
Yes, but gpa still doesn't work
-------- Original Message --------

**Comment by romanz** [comment]
Thanks for opening this issue, and sorry for the delayed response.
Could you please attach the logs of trezor-gpg-agent?

**Comment by gordonel** [comment]
After some trickery I managed to get it to work with Keybase and prove my PGP key. I can try spinning up another instance of my OS and creating another key though. What exactly would you like me to do?

**Comment by grnqrtr** [comment]
@gordonel What exactly did you do to get keybase to recognize your Trezor's PGP key? I'm in the same boat. I'm running Manjaro Linux 19.0.2.

**Comment by gordonel** [comment]
@grnqrtr I vaguely remember, but placed the trezor GPG stuff into the default GPG directory and changed the path back to default. Then I used keybase CLI to add the key

**Comment by grnqrtr** [comment]
I'm been trying moving the trezor GPG stuff around and changing the $GNUPGHOME path to various things. Have tried on both Manjaro Linux and a Debian based system, but no luck yet. I'll try posting in Keybase's github too. Here's info if anyone else has any input for me:

```
[grnqrtr@manjaro ~]$ echo $GNUPGHOME
/home/grnqrtr/.gnupg/trezor
[grnqrtr@manjaro ~]$ gpg -K         
/home/grnqrtr/.gnupg/trezor/pubring.kbx
---------------------------------------
sec   nistp256 2020-03-27 [SC]
      C6515C3CB09D83CCD614A4B70DB3437DA47ECB2F
uid           [ultimate] Travis Kilson <travis.kilson@gmail.com>
ssb   nistp256 2020-03-27 [E]

[grnqrtr@manjaro ~]$ keybase pgp select
You are selecting a PGP key from your local GnuPG keychain, and
will publish a statement signed with this key to make it part of
your Keybase.io identity.

Note that GnuPG will prompt you to perform this signature.

You can also import the secret key to *local*, *encrypted* Keybase
keyring, enabling decryption and signing with the Keybase client.
To do that, use "--import" flag.

Learn more: keybase pgp help select

▶ ERROR No PGP keys available to choose from.
```

**Comment by dragon788** [comment]
This is due to a change in Keybase in how they discover which Gpg configs to use. https://github.com/keybase/client/issues/8030#issuecomment-681980304
